version: "3.1"

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public public/index.php
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - ./logs:/var/www/logs
    db:
      image: mysql
      network_mode: host
      environment:
          MYSQL_ROOT_PASSWORD: pass4mysql
      volumes:
          - ./data:/var/lib/mysql