version: "3.1"

services:
    slim:
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public public/index.php
        environment:
            docker: "true"
        ports:
            - 8081:8080
        volumes:
            - .:/var/www
            - ./logs:/var/www/logs
    db:
      image: mysql
      ports:
          - 3310:3306
      environment:
          MYSQL_ROOT_PASSWORD: pass4mysql
          MYSQL_DATABASE: titan-gym
      volumes:
          - ./data:/var/lib/mysql
